# https://cloud.google.com/appengine/docs/the-appengine-environments#comparing_high-level_features
# https://cloud.google.com/appengine/docs/standard

runtime: java17
instance_class: F2
env_variables:
  SPRING_PROFILES_ACTIVE: 'gcp'
  APP_PLAYER_DATASOURCE_URL: 'jdbc:mysql://<35.204.19.36>:3306/playerdb'
  APP_PLAYER_DATASOURCE_USERNAME: '<username>'
  APP_PLAYER_DATASOURCE_PASSWORD: '<password>'

management:
  endpoints:
    web:
      exposure:
        include: shutdown